# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  -
    package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 20
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - ci
      - priority-low
      - maintenance
    groups:
      github-actions:
        patterns:
          - "*"

  -
    package-ecosystem: npm
    directory: /
    versioning-strategy: increase
    open-pull-requests-limit: 20
    reviewers:
      - AliMD
    schedule:
      interval: daily
    labels:
      - dependencies
      - ci
      - priority-low
      - maintenance
    groups:
      production-dependencies:
        dependency-type: "production"
        exclude-patterns:
          - "@alwatr/*"
          - "fract"
      development-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - "*lint*"
          - "@alwatr/*"
          - "fract"
      lint-dependencies:
        patterns:
          - "*lint*"
      alwatr-dependencies:
        patterns:
          - "@alwatr/*"
          - "fract"
