networks:
  internal:
  alwatr-public-network:
    name: alwatr-public-network
    external: true

services:
  cdn:
    image: $CDN_IMAGE

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      alwatr-public-network:

    environment:
      - NGINX_ACCESS_LOG=${CDN_ACCESS_LOG:-off}

    volumes:
      - type: bind
        source: ./_data/
        target: /var/www/html/
        bind:
          create_host_path: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${DOMAIN}; PathPrefix:/
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https
