networks:
  internal:
  alwatr-public-network:
    name: alwatr-public-network
    external: true

services:
  storage-server:
    image: ghcr.io/alimd/storage-server:${STORAGE_SERVER_VERSION}

    cpu_count: 1
    cpu_shares: 1024
    mem_limit: 256m

    stop_grace_period: 30s

    restart: unless-stopped

    networks:
      internal:
        aliases:
          - '${APP_ID}-storage-server'

    environment:
      - STORAGE_PATH=/storage
      - ACCESS_TOKEN=${STORAGE_ACCESS_TOKEN}
      - ALWATR_DEBUG=${STORAGE_SERVER_DEBUG:-}

    volumes:
      - type: bind
        source: ./_data/storage
        target: /storage
        bind:
          create_host_path: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

  telegram-bot:
    image: ghcr.io/alimd/day-countdown-bot:${TELEGRAM_BOT_VERSION:-next}

    cpu_shares: 1024
    mem_limit: 256m

    restart: unless-stopped

    networks:
      internal:
      alwatr-public-network:

    environment:
      - STORAGE_HOST=${APP_ID}-storage-server
      - STORAGE_PORT=80
      - STORAGE_TOKEN=${STORAGE_ACCESS_TOKEN}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_BOT_WEBHOOK_DOMAIN=${TELEGRAM_BOT_WEBHOOK_DOMAIN}
      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME}
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - ALWATR_DEBUG=${TELEGRAM_BOT_DEBUG:-}

    volumes:
      - type: bind
        source: ./_data/storage
        target: /storage
        bind:
          create_host_path: true

    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '2'

    labels:
      traefik.enable: true
      traefik.port: 80
      traefik.frontend.rule: Host:${TELEGRAM_BOT_WEBHOOK_DOMAIN}
      traefik.frontend.entryPoints: http, https
      traefik.frontend.redirect.entryPoint: https
